#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_ENABLED_PATH/common/functions"

APP="$1"
IMAGE=$(get_app_image_name $APP)

verify_app_name "$APP"

dokku_log_info1 "Populate env vars for database ..."

URL=($(echo $DATABASE_URL | sed -e 's/\(.*\)\:\/\/\(.*\):\(.*\)\@\(.*\)\:\(.*\)\/\(.*\)/\1 \2 \3 \4 \5 \6/'))

EXPORTS="export DATABASE_TYPE='${URL[0]}'
export DATABASE_USER='${URL[1]}'
export DATABASE_PASSWORD='${URL[2]}'
export DATABASE_HOST='${URL[3]}'
export DATABASE_PORT='${URL[4]}'
export DATABASE_NAME='${URL[5]}'"

# Add database env vars
id=$("$DOCKER_BIN" run "--label=com.dokku.app-name=${APP}" $DOKKU_GLOBAL_RUN_ARGS -d $IMAGE /bin/bash -c "mkdir -p /app/.profile.d/ && echo -e \"$EXPORTS\" > /app/.profile.d/extract_db_env.sh")

test $("$DOCKER_BIN" wait $id) -eq 0

DOKKU_COMMIT_ARGS=("--change" "LABEL org.label-schema.schema-version=1.0" "--change" "LABEL org.label-schema.vendor=dokku" "--change" "LABEL $DOKKU_CONTAINER_LABEL=")
"$DOCKER_BIN" commit --change "LABEL com.dokku.app-name=$APP" "${DOKKU_COMMIT_ARGS[@]}" $id $IMAGE > /dev/null
